---
- name: Apt update
  apt: 
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Get Mellanox Firmware
  get_url:
    url: http://content.mellanox.com/ofed/MLNX_OFED-{{mlnx_ver}}/MLNX_OFED_LINUX-{{mlnx_ver}}-{{arch}}.tgz
    dest: /srv/MLNX_OFED_LINUX-{{mlnx_ver}}-{{arch}}.tgz

- name: unarchive Mellanox Firmware
  unarchive:
    remote_src: true
    src: /srv/MLNX_OFED_LINUX-{{mlnx_ver}}-{{arch}}.tgz
    dest: /srv/
    creates: /srv/MLNX_OFED_LINUX-{{mlnx_ver}}-{{arch}}

- name: install main Debian prereqs
  apt:
#           debhelper python-libxml2 quilt autoconf libnuma1 pkg-config m4 pciutils ethtool gcc dpatch automake chrpath swig autotools-dev graphviz libltdl-dev dkms linux-headers-4.15.0-20-generic
    name: ['ethtool','tcl','libelf1','libnl-route-3-200','swig','libnuma1','quilt','python-libxml2','libltdl-dev','dkms','tk','gfortran','chrpath','pciutils','dpatch','pkg-config']
  when: ansible_os_family == 'Debian'

- name: install centos prereqs
  yum:
    name: ['lsof', 'rdma-core', 'rdma-core-devel']
  when: ansible_os_family == 'RedHat'

- name: install debhelper for Debian
  apt:
    name: 'debhelper'
  when: ansible_os_family == 'Debian'

- name: run Mlnx OFED install
  command: "./mlnxofedinstall --dpdk --force{{ ' --upstream-libs' if ansible_os_family == 'Debian' else '' }}"
  args:
    chdir: /srv/MLNX_OFED_LINUX-{{mlnx_ver}}-{{arch}}

    # NOTE: key download is a seperate step since the key file is referenced by the created repo file
- name: Get Mellanox GPG key for repo setup
  get_url:
    url: http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
    dest: /root/RPM-GPG-KEY-Mellanox
  when: ansible_os_family == 'RedHat'

- name: Install Mellanox GPG key for repo setup
  rpm_key:
    key: /root/RPM-GPG-KEY-Mellanox
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install REPO for Mellanox upstream libs
  template:
    src: mlnx_ofed.repo.j2
    dest: /etc/yum.repos.d/mlnx_ofed.repo
  when: ansible_os_family == 'RedHat'

 # Note: this comes after executing mlnxofedinstall script because said scropt will uninstall these as part of its run
- name: Install Mellanox upstream libs
  yum:
    name: mlnx-ofed-dpdk-upstream-libs
  when: ansible_os_family == 'RedHat'

- name: remove ib_srpt
  command: modprobe -rv ib_srpt

- name: restart openibd service
  service:
    name: openibd
    state: restarted

