{{ range $k, $v := .Values.cnf }}
---
apiVersion: v1 
kind: Pod
metadata:
  name: vpp-{{$k}}
  labels:
    app: vpp
    chart: vpp-0.1.0
  annotations:
    k8s.v1.cni.cncf.io/networks: ipfwd-bridge
spec:
  containers:    
  - name: {{ $.Chart.Name }}-{{$k}}
    image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
    imagePullPolicy: {{ $.Values.image.pullPolicy }}
    securityContext:
      privileged: {{ $.Values.privileged }}
    resources:
{{ toYaml $.Values.resources | indent 12 }}
    readinessProbe:
      exec:
        command: ["vppctl", "show ver"]
      initialDelaySeconds: 5
      periodSeconds: 30
    volumeMounts:
    - name: config-volume
      subPath: startup_{{$k}}.conf
      mountPath: /etc/vpp/startup.conf
    - name: config-volume
      subPath: setup_{{$k}}.gate
      mountPath: /etc/vpp/setup.gate
    - name: vpp-sockets
      mountPath: {{ $.Values.volumeMounts.vpp_sockets.mountPath }}
    - name: hugepage
      mountPath: /hugepages
  volumes:
  - name: config-volume
    configMap:
      name: vpp-configmap
      items:
      - key: startup_{{$k}}.conf
        path: startup_{{$k}}.conf
      - key: setup_{{$k}}.gate
        path: setup_{{$k}}.gate
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: vpp-sockets
    hostPath:
      path: /etc/vpp/sockets/
{{ end }}
