---
- name: restart nova-compute
  service:
    name: nova-compute
    state: restarted
  when: ansible_os_family == 'Debian'

- name: restart nova-compute
  service:
    name: openstack-nova-compute
    state: restarted
  when: ansible_os_family == 'RedHat'

- name: restart neutron-server
  service:
    name: neutron-server
    state: restarted

- name: restart ovs-agent
  service:
    name: neutron-openvswitch-agent
    state: restarted

- name: restart dhcp-agent
  service:
    name: neutron-dhcp-agent
    state: restarted

- name: restart metadata-agent
  service:
    name: neutron-metadata-agent
    state: restarted
